Disable-NetAdapterBinding -name "*" -ComponentID "ms_server"
Disable-NetAdapterBinding -name "*" -ComponentID "ms_msclient"
Disable-NetAdapterBinding -name "*" -ComponentID "ms_rspndr"
Disable-NetAdapterBinding -name "*" -ComponentID "ms_lltdio"
Disable-NetAdapterBinding -name "*" -ComponentID "ms_tcpip6"